# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54ce7f5e70175c5e74f1f77623365474428a56d424e39bfe8b15da276d3c2f40e3576ed475edd7ebc69511eff6a2416a828721889216e6316477fb2b5c1b57a1

test:
  secret_key_base: 8b53ca98b703ee8db780e0eeb88694d1fdee44f3b755c74c0452eb93cd2f78d3e3375b9154b76126d6382d47ff32446ad091a0b9a2929d440da78c6496ee4b2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
